spring.application.name=groceryapp

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/grocery_app
spring.datasource.username=root
spring.datasource.password=priyanpolice

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080